### ISSUE TITLE
曉雯的測試結果

### ISSUE THREAD

**Issue by ChihChengLiang** [TaiwanRUserGroup/DSC2015Tutorial#16]
Swirl選單：
3和5以及4和6 一樣 ??（如下圖）
<img width="469" alt="2015-08-19-0" src="https://cloud.githubusercontent.com/assets/3391420/9349032/7050d7ae-4672-11e5-89d8-f6425d5b3636.png">

**R basic Ning 投影片**
Page 7, 9 是空白的
    Page 27 直方圖看不見橫軸
    Page 71 看不見substring例子
    Page 81, 82.83 圖片秀不出來
    Page 98 把markdown的code秀出來了？
**R basic Noah 投影片**
Page 44 圖不見了
Page 53 第六個[1] "log of 10 = 2.30258509299405" 沒秀出來？
Page 54 其他output沒秀出來？

Swirl:
1. Learn Swirl：ＯＫ
    2. R Basic Part 0-The Basics：ＯＫ
    3. R Basic Part 1-Data Structure in R：ＯＫ
    4. R Basic Part 1-Simple Data Analysis：ＯＫ
    7. R Basic Part 3-Function：ＯＫ
1. R Basic Part 4-Control Flow and Exception Handling：不能執行？（如下圖）
   <img width="545" alt="2015-08-19-1" src="https://cloud.githubusercontent.com/assets/3391420/9349048/a5cbcae2-4672-11e5-884b-343946e92e4c.png">
2. R Basic Part 4-If Else：ＯＫ
3. R Basic Part 5-For：ＯＫ
4. R Basic Part 6-Debug And Undebug：ＯＫ
5. R Basic Part 7-try And tryCatch：ＯＫ

**Comment by wush978** [comment]
關於重複的課程名稱，應該是因為沒有先uninstall之前裝過的課程，不算是bug!

**Comment by wush978** [comment]
太感謝了
