### ISSUE TITLE
getURLContent出錯

### ISSUE THREAD

**Issue by robert0714** [TaiwanRUserGroup/DSC2015Tutorial#25]
getURLContent("http://data.taipower.com.tw/opendata/apply/file/d003002/001.txt",.encoding = "UTF16")
Error in curlPerform(url = url, curl = curl, .opts = .opts) : 
  空值嵌入於字串中：'\xff\xfet^%R(\0\021l\vW)\0\t\0\026\\xf0\\xa0\x8c\t\x8f(\0,\x84\xe9t)\0\t\0\x99P(u\xb9[ϑ\x87s(\0%\0)\0\r\0\n\07\01\0\t\06\09\01\0.\08\0\t\0\t\02\06\0.\08\0\r\0\n\07\02\0\t\07\08\00\0.\08\0\t\0\t\02\09\0.\02\0\r\0\n\07\03\0\t\08\05\01\0.\07\0\t\0\t\02\02\0.\01\0\r\0\n\07\04\0\t\08\07\01\0.\06\0\t\0\t\05\05\0.\01\0\r\0\n\07\05\0\t\09\09\00\0.\00\0\t\0\t\04\08\0.\03\0\r\0\n\07\06\0\t\01\0,\01\01\01\0.\03\0\t\0\t\03\05\0.\00\0\r\0\n\07\07\0\t\01\0,\02\03\03\0.\01\0\t\0\t\02\01\0.\07\0\r\0\n\07\08\0\t\01\0,\03\04\02\0.\02\0\t\0\t\01\04\0.\00\0\r\0\n\07\09\0\t\01\0,\04\05\01\0.\01\0\t\0\t\07\0.\04\0\r\0\n\08\00\0\t\01\0,\05\03\02\0.\01\0\t\0\t\04\0.\08\0\r\0\n\08\01\0\t\01\0,\06\07\00\0.\04\0\t\0\t\06\0.\07\0\r\0\n\08\02\0\t\01\0,\07\06\06\0.\06\0\t\0\t\04\0.\02\0\r\0\n\08\03\0\t\01\0,\08\06\01\0.\00\0\t\0\t\04\0.\08\0\r\0\n\08\04\0\t\01\0,\09\09\03\0.\03\0\t\0\t\04\0.\07\0\r\0\n\08\05\0\t\02\0,\01\07\06\0.\02\0\t\0\t\05\0.\06\0\r\0\n\08\06\0\t\02\0,\0

**Comment by robert0714** [comment]
> sessionInfo()
> R version 3.2.1 (2015-06-18)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.5 (Yosemite)

locale:
[1] zh_TW.UTF-8/zh_TW.UTF-8/zh_TW.UTF-8/C/zh_TW.UTF-8/zh_TW.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RCurl_1.95-4.7   bitops_1.0-6     DSC2015R_1.0     swirl_2.2.21     ggplot2_1.0.1    dplyr_0.4.1      data.table_1.9.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6      knitr_1.11       xml2_0.1.1       magrittr_1.5     devtools_1.8.0   MASS_7.3-43      munsell_0.4.2  
 [8] colorspace_1.2-6 R6_2.1.0         stringr_1.0.0    httr_1.0.0       plyr_1.8.3       tools_3.2.1      parallel_3.2.1  
[15] grid_3.2.1       gtable_0.1.2     DBI_0.3.1        git2r_0.11.0     rversions_1.0.2  yaml_2.1.13      assertthat_0.1  
[22] digest_0.6.8     crayon_1.3.1     reshape2_1.4.1   testthat_0.10.0  curl_0.9.1       memoise_0.2.1    stringi_0.5-5  
[29] scales_0.2.5     chron_2.3-47     proto_0.3-10

**Comment by wush978** [comment]
先下載網頁到`~/Downloads/001.txt`
然後

```
file.info("~/Downloads/001.txt")$size
raw <- readBin("~/Downloads/001.txt", what = "raw", n = 1212)
raw2 <- raw[3:length(raw)]
tail(raw, -2)
writeBin(raw2, con = tmp.path2 <- tempfile())
read.table(file(tmp.path2, encoding = "UTF-16LE"), header = T, sep = "\t")
```

**Comment by wush978** [comment]
請問這樣能夠解決你的問題嗎？

**Comment by robert0714** [comment]
有!!!謝謝你！！！

**Comment by ChihChengLiang** [comment]
```
> t = read.table(file(tmp.path2, encoding = "UTF-16LE"), header = T, sep = "\t")
> head(t)
   年別.民國. 尖峰負載.萬瓩. 備用容量率...
71      691.8             NA          26.8
72      780.8             NA          29.2
73      851.7             NA          22.1
74      871.6             NA          55.1
75      990.0             NA          48.3
76    1,111.3             NA          35.0
```

**Comment by robert0714** [comment]
有～～謝謝你
