### ISSUE TITLE
無法下載DSC2015R package

### ISSUE THREAD

**Issue by pseudolapiz** [TaiwanRUserGroup/DSC2015Tutorial#34]
如標題，最近在教實驗室的小朋友學R，
前兩天下載DSC2015R package還可以，
今天下載就出現以下錯誤訊息...

> install.packages("DSC2015R")
> Installing package into ‘C:/Users/User/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘DSC2015R’ is not available (for R version 3.2.1)

**Comment by jackchen0309** [comment]
Hi,

```
要檢查R版本, DSC2015R似乎是無法在R 3.2.1版本使用,所以無法安裝.
```

Cheers,
Jack

2015-12-02 15:44 GMT+08:00 pseudolapiz notifications@github.com:

**Comment by pseudolapiz** [comment]
我是3.2.1沒錯，但我前兩天有安裝成功耶?

我更新一下看還有沒有問題。

另外DSC2014也不能裝了Orz

**Comment by pseudolapiz** [comment]
剛剛更新到3.2.2，又可以了耶
奇怪，那我之前3.2.1的時候怎麼裝的...

**Comment by pseudolapiz** [comment]
問題解決，感謝大家。DSC2014不能裝的問題與這邊無關，這個討論先關閉了。
