### ISSUE TITLE
您好~關於R語言自學

### ISSUE THREAD

**Issue by cmelo1515** [TaiwanRUserGroup/DSC2015Tutorial#36]
您好
我RSTUDIO已安裝完畢，現在想要看影片，已經成功開啟影片網址，但是卻沒有影片顯示，請問是連結已經關閉了嗎?謝謝

**Comment by wush978** [comment]
之前上傳的影片我不滿意，所以刪除了喔！
先麻煩你依照 http://wush978.github.io/DataScienceAndR 的說明做操作吧
